# Access SMPL models.
smplx_models: "/is/cluster/fast/mkeller2/Data/body_model/smplx_models" #"/ps/project/rib_cage_breathing/TML/Data/smplx_models"
star_models: "../data/star_models"
supr_models: "../data/supr_models"
skel_models: "/is/cluster/work/mkeller2/Data/TML/Release/v1.0/skel_models_v1.1"
osim_geometry : "/is/cluster/work/mkeller2/Data/TML/Release/v1.0/skel_models_v1.1/Geometry"

# Access to datasets.
datasets:
  amass:
    "/is/cluster/work/mkeller2/Data/TML/AMASS"
  bioamass:
    "/is/cluster/work/mkeller2/Data/TML/Release/v1.0/bioamass_v1.0"
  amass_mocap:
    "/is/cluster/work/mkeller2/Data/TML/AMASS_mocap" 

# Pytorch configuration.
device: "cpu"
f_precision: 32
i_precision: 64

# Camera.
znear: 0.01
zfar: 1000.0
camera_zoom_speed: 0.05

# Viewer.
window_width: 1600
window_height: 900
fullscreen: False
resizable: True
vsync: True
export_dir: "../export"
playback_fps: 60
scene_fps: 60
run_animations: False
dark_mode: False
shadows_enabled: True
auto_set_floor: True
auto_set_camera_target: True
backface_culling: True
background_color: [1.0, 1.0, 1.0, 1.0]
window_type: "pyglet" # window_type: "pyqt5" 


# Viewer defaults to Y up, set to true for Z up.
z_up: False

# Server for remote connections.
server_enabled: True
server_port: 8417
